apiVersion: v1
kind: Service
metadata:
  name: basyx-aas-server
  labels:
    app.kubernetes.io/name: idta-submodel-editor
    app.kubernetes.io/component: basyx-aas-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: idta-submodel-editor
    app.kubernetes.io/component: basyx-aas-server
  ports:
  - name: http
    port: 4001
    targetPort: 4001
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: basyx-registry
  labels:
    app.kubernetes.io/name: idta-submodel-editor
    app.kubernetes.io/component: basyx-registry
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: idta-submodel-editor
    app.kubernetes.io/component: basyx-registry
  ports:
  - name: http
    port: 4002
    targetPort: 4002
    protocol: TCP
