---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-dataspace-pvc
  labels:
    app.kubernetes.io/name: idta-submodel-editor
    app.kubernetes.io/component: dataspace-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data-pvc
  labels:
    app.kubernetes.io/name: idta-submodel-editor
    app.kubernetes.io/component: dataspace-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basyx-data-pvc
  labels:
    app.kubernetes.io/name: idta-submodel-editor
    app.kubernetes.io/component: dataspace-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
