apiVersion: v1
kind: Service
metadata:
  name: dtr
  labels:
    app.kubernetes.io/name: idta-submodel-editor
    app.kubernetes.io/component: dtr
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: idta-submodel-editor
    app.kubernetes.io/component: dtr
  ports:
  - name: http
    port: 4003
    targetPort: 4003
    protocol: TCP
