apiVersion: v1
kind: Service
metadata:
  name: edc-data-plane
  labels:
    app.kubernetes.io/name: idta-submodel-editor
    app.kubernetes.io/component: edc-data-plane
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: idta-submodel-editor
    app.kubernetes.io/component: edc-data-plane
  ports:
  - name: default
    port: 19290
    targetPort: 19290
    protocol: TCP
  - name: public
    port: 19291
    targetPort: 19291
    protocol: TCP
  - name: control
    port: 19292
    targetPort: 19292
    protocol: TCP
